import Chip from "@/components/Chip/Chip";

export const reportDummyData = [
    {
      name: 'Bitcoin',
      symbol: 'BTC',
      image: "https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400",
      comfortRating: <Chip label="Uncomfortable" bgColor="var(--color-error-50)" />,
      marketCap: 120000,
    },
    {
      name: 'Ethereum',
      symbol: 'ETH',
      image: "https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 180000,
    },
    {
      name: 'XRP',
      symbol: 'XRP',
      image: "https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501682",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 1860000,
    },
    {
      name: 'Tether',
      symbol: 'USDT',
      image: "https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 860000,
    },
    {
      name: 'BNB',
      symbol: 'BNB',
      image: "https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501986",
      comfortRating: <Chip label="Uncomfortable" bgColor="var(--color-error-50)" />,
      marketCap: 1860900,
    },
    {
      name: 'Solana',
      symbol: 'SOL',
      image: "https://coin-images.coingecko.com/coins/images/4128/large/Solana.png?1696504182",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 9860000,
    },
    {
      name: 'USDC',
      symbol: 'USDC',
      image: "https://coin-images.coingecko.com/coins/images/6319/large/usdc.png?1696506694",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 19860000,
    },
    {
      name: 'Dogecoin',
      symbol: 'DOGE',
      image: "https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409",
      comfortRating: <Chip label="Uncomfortable" bgColor="var(--color-error-50)" />,
      marketCap: 89860000,
    },
    {
      name: 'TRON',
      symbol: 'TRX',
      image: "https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png?1696502096",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 9860000,
    },
    // New coins from last extraction
    {
      name: "Wrapped stETH",
      symbol: "WSTETH",
      image: "https://coin-images.coingecko.com/coins/images/18834/large/wstETH.png?1696518295",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 9870000,
    },
    {
      name: "Hyperliquid",
      symbol: "HYPE",
      image: "https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300",
      comfortRating: <Chip label="Uncomfortable" bgColor="var(--color-error-50)" />,
      marketCap: 9870090,
    },
    {
      name: "Stellar",
      symbol: "XLM",
      image: "https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 9870097,
    },
    {
      name: "Sui",
      symbol: "SUI",
      image: "https://coin-images.coingecko.com/coins/images/26375/large/sui-ocean-square.png?1727791290",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 19870097,
    },
    {
      name: "Chainlink",
      symbol: "LINK",
      image: "https://coin-images.coingecko.com/coins/images/877/large/chainlink-new-logo.png?1696502009",
      comfortRating: <Chip label="Uncomfortable" bgColor="var(--color-error-50)" />,
      marketCap: 198700970,
    },
    {
      name: "Hedera",
      symbol: "HBAR",
      image: "https://coin-images.coingecko.com/coins/images/3688/large/hbar.png?1696504364",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 198700970,
    },
    {
      name: "Bitcoin Cash",
      symbol: "BCH",
      image: "https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 8198700970,
    },
    {
      name: "Avalanche",
      symbol: "AVAX",
      image: "https://coin-images.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png?1696512369",
      comfortRating: <Chip label="Uncomfortable" bgColor="var(--color-error-50)" />,
      marketCap: 18198700970,
    },
    {
      name: "Wrapped eETH",
      symbol: "WEETH",
      image: "https://coin-images.coingecko.com/coins/images/33033/large/weETH.png?1701438396",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 2198700970,
    },
    {
      name: "Shiba Inu",
      symbol: "SHIB",
      image: "https://coin-images.coingecko.com/coins/images/11939/large/shiba.png?1696511800",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 2198700975,
    },
    {
      name: "LEO Token",
      symbol: "LEO",
      image: "https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 72198700975,
    },
    {
      name: "WETH",
      symbol: "WETH",
      image: "https://coin-images.coingecko.com/coins/images/2518/large/weth.png?1696503332",
      comfortRating: <Chip label="Uncomfortable" bgColor="var(--color-error-50)" />,
      marketCap: 92198700975,
    },
    {
      name: "Toncoin",
      symbol: "TON",
      image: "https://coin-images.coingecko.com/coins/images/17980/large/photo_2024-09-10_17.09.00.jpeg?1725963446",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 2198700979,
    },
    {
      name: "Litecoin",
      symbol: "LTC",
      image: "https://coin-images.coingecko.com/coins/images/2/large/litecoin.png?1696501400",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 9876543,
    },
    {
      name: "USDS",
      symbol: "USDS",
      image: "https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683",
      comfortRating: <Chip label="Uncomfortable" bgColor="var(--color-error-50)" />,
      marketCap: 1234567,
    },
    {
      name: "Binance Bridged USDT (BNB Smart Chain)",
      symbol: "BSC-USD",
      image: "https://coin-images.coingecko.com/coins/images/35021/large/USDT.png?1707233575",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 9876543,
    },
    {
      name: "Polkadot",
      symbol: "DOT",
      image: "https://coin-images.coingecko.com/coins/images/12171/large/polkadot.png?1696512008",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 5678901,
    },
    {
      name: "WhiteBIT Coin",
      symbol: "WBT",
      image: "https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096",
      comfortRating: <Chip label="Uncomfortable" bgColor="var(--color-error-50)" />,
      marketCap: 3456789,
    },
    {
      name: "Uniswap",
      symbol: "UNI",
      image: "https://coin-images.coingecko.com/coins/images/12504/large/uniswap-logo.png?1720676669",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 6789012,
    },
    {
      name: "Monero",
      symbol: "XMR",
      image: "https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 4567890,
    },
    {
      name: "Coinbase Wrapped BTC",
      symbol: "CBBTC",
      image: "https://coin-images.coingecko.com/coins/images/40143/large/cbbtc.webp?1726136727",
      comfortRating: <Chip label="Uncomfortable" bgColor="var(--color-error-50)" />,
      marketCap: 123456789,
    },
    {
      name: "Ethena USDe",
      symbol: "USDE",
      image: "https://coin-images.coingecko.com/coins/images/33613/large/usde.png?1733810059",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 23456789,
    },
    {
      name: "Bitget Token",
      symbol: "BGB",
      image: "https://coin-images.coingecko.com/coins/images/11610/large/Bitget_logo.png?1736925727",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 34567890,
    },
    {
      name: "Pepe",
      symbol: "PEPE",
      image: "https://coin-images.coingecko.com/coins/images/29850/large/pepe-token.jpeg?1696528776",
      comfortRating: <Chip label="Uncomfortable" bgColor="var(--color-error-50)" />,
      marketCap: 45678901,
    },
    {
      name: "Aave",
      symbol: "AAVE",
      image: "https://coin-images.coingecko.com/coins/images/12645/large/aave-token-round.png?1720472354",
      comfortRating: <Chip label="Comfortable" bgColor="var(--color-success-50)" />,
      marketCap: 56789012,
    },
  ];